### ISSUE TITLE
Is it necessary to inject the DLL with UUU for The MS Store version ? The exe is accessible.

### ISSUE THREAD

**Issue by amine4567** [emoose/DQXIS-SDK#21]
Hello,

I am wondering if it's necessary to inject the xinput1_3.dll using something like UUU when using the MS Store version of the game before each launch. Because the executable is actually accessible in the windows explorer like so:

C:\Program Files\WindowsApps\<SOME_HEX_STRING>.DQXISWW_1.0.4.0_x64__<SOME_OTHER_HEX_STRING>\Game\Binaries\Win64\DRAGON QUEST XI S.exe

Would putting the xinput1_3.dll next to the exe work without needing to inject it each time ?

**Comment by emoose** [comment]
Hmm, I don't own the MS Store version so not sure myself, but I've been told getting the access to write into that folder can take some effort.

If you're able to write there then placing the file there as you've described should hopefully work, otherwise maybe something like https://github.com/SEWsam/UWP-DOOMdumper can help make a writable version.

If you get something working let me know and I'll try updating the MS Store instructions.

**Comment by amine4567** [comment]
Indeed, you can't write in the folder of the MS Store version of the game, I hadn't checked that.

I tried to do something similar to what UWP-DOOMdumper does, I used UWPDumper to dump the game files somewhere else and then I used powershell commands to delete the original folder and register the new one as a windows app. 

It works, the game launches well with the new path from the xbox app but the game shows me "unknown error" and "corrupted save". I tried deleting the saves from the saves folder of the game but the problem still persist. 

I think this method should work with enough effort, I just don't want to bother with it right now. I also wonder if achievements would still work if the game is in a custom install location ?

Anyway, I uninstalled and reinstalled the game in its original folder (so read-only). I will use the UUU to inject the dll at each launch for now.

I have one last question: If I inject the modded xinput and close UUU, does the dll stay injected? 

I want to do this because I have an ultrawide monitor and the only way I found to run the game ultrawide is to inject UniversalUE4Unlocker.dll to use custom resolutions. In short I need to inject your DLL and UniversalUE4Unlocker.dll at the same time.

**Comment by emoose** [comment]
Ah that's too bad about the save issue, wonder if the DOOM tool had to work around anything like that.

Closing UUU after injecting should be fine, should stay injected until you close the game AFAIK.
If you're using UniversalUE4Unlocker.dll to set the res via the dev-console there's not really any need since DQXIS-SDK also has a console-unlocker, shouldn't be any harm though I guess since they probably unlock it differently there.

**Comment by amine4567** [comment]
When using DQXIS-SDK, the dev-console shortcut didn't work for me, neither did trying to change the resolution in the UUU UI. Maybe I wasn't using it right ?

**Comment by emoose** [comment]
Oh hm, is your keyboard layout something different than English-UK/English-US? You might need to change to one of those for it to work.

If you can edit the Input.ini file you could change the key to something else too, without needing to change kb layout, there's info on that here: https://github.com/emoose/DQXIS-SDK/issues/8#issuecomment-790688355
I'm not sure if MS Store might hide away the Input.ini somewhere though, hopefully not.

There's also a chance the MS Store version I coded this for was an older build, is there any chance you could create a hash checksum of your DRAGON QUEST XI S.exe file? http://implbits.com/products/hashtab/ is useful for that.

**Comment by amine4567** [comment]
Yes, I am using a french keyboard. Following the instructions in the attached issue worked, the dev-console is accessible now. Thanks !
