### ISSUE TITLE
Steam update (5/28/21) removed Denuvo, breaking DQXI-SDK

### ISSUE THREAD

**Issue by mike9k1** [emoose/DQXIS-SDK#23]
https://steamdb.info/app/1295510/history/?changeid=U:23098371

Hopefully only the addresses being checked at startup need to be changed in order to work with the new update.

Edit: Tried a build without the check and unfortunately got a crash. Good news is that GHFear's build of DQXISHook (which uses AoB signatures) still works with this version. 

If any help is needed updating DQXI-SDK to work with the new update, we could probably forward things your way. My guess is that I probably missed something else (i.e. an address) that was hardcoded somewhere causing the crash. Hopefully it shouldn't be too bad getting things working again.

**Comment by DisarmedSpy** [comment]
Same here

**Comment by emoose** [comment]
Should be fixed in 0.7.5.1 hopefully - seemed to work for users on Steam forums at least, I haven't tested it myself though. I'm hoping it'll work with the JP release too (don't have a non-Denuvo JP EXE to check with, but since JP matched up with WW before hopefully it'll be fine)

Like mentioned on Steam forums, this new update is actually an older EXE from a few hours before the last updates EXE, I'm guessing this update probably pushed the original non-Denuvo EXE that the Denuvo-ized version was based on - at least all the code offsets are the same.
